### ISSUE TITLE
Fix `isExpiring` function types

### ISSUE THREAD

**Issue by fregante** [fregante/webext-storage-cache#13]
https://github.com/sindresorhus/refined-github/pull/2667#discussion_r365601322

```ts
	isExpired: (cachedValue: any) => typeof cachedValue === 'string',
```

The correct type would allow `OldType | NewType` (because the cache is either in the old format or the new format) but the current types don't allow that doesn't allow that, so `any` is the only option available.

**Comment by hardikmodha** [comment]
Hi, Not sure if it's valid. Because as I commented on https://github.com/sindresorhus/refined-github/pull/2667#discussion_r368231745, I can provide other types to `isExpired` function.
