### ISSUE TITLE
Accept a plain string as `cacheKey` in `cache.function`

### ISSUE THREAD

**Issue by fregante** [fregante/webext-storage-cache#17]
# Currently

`cacheKey` is a function

```js
const cachedFunction = cache.function(someFunction, {
	cacheKey: ([parameter]) => 'unique:' + parameter
});
```

# Ideally

`cacheKey` could also accept a string that will automatically use the function’s arguments as `[cacheKey, ...args].join(':')`

```js
const cachedFunction = cache.function(someFunction, {
	cacheKey: 'unique'
});
```

This would work in cases where `someFunction` accepts stringifiable arguments.

**Comment by cheap-glitch** [comment]
How about allowing a string in `cacheKey` to set a static key, and having an additional parameter named e.g. `cacheKeyPrefix` for the key + arguments behavior?

**Comment by fregante** [comment]
They’re equivalent. If you need to vary depending on the argument, then they will be appended to the supplied string; if you call the function without any arguments, then the string will be used as is.

```
[cacheKey, ...args].join(':')
```

**Comment by cheap-glitch** [comment]
> Accepting a raw cacheKey string and then not varying based on the arguments would be a mistake.

Not necessarily, one might want to purposefully ignore the arguments passed to the function. Though maybe in that case might as well use `cache.set()` directly :thinking:

**Comment by fregante** [comment]
It turns out the current logic is just bad all-around:

- a name should always be required; passing `cache.function` without a `cacheKey` guarantees conflicts
	```js
    const quareCached = cache.function(square);
    const cubeCached = cache.function(cube);
    quareCached(2) === cubeCached(2)
	```
- considering just the first argument makes sense for `mem`, where objects are stored by reference, but makes less sense here, where all arguments are turned into a string anyway (which must be stringifable)

I'm making some changes in https://github.com/fregante/webext-storage-cache/pull/39:

- make `cacheName` required
- default to `cacheKey: JSON.stringify`

Thoughts?

**Comment by fregante** [comment]
Two notes:

- I thought about using `function.name` as a default but that's bad with bundlers and minifiers. Even with an explicit `fn.name = 'style-fixes'` it'd be more awkward than just providing a mandatory option
- since `cacheName` is now used to build the key, does `cacheKey` still make sense as a name? Maybe they should be named `name` and `argumentSerializer`

**Comment by fregante** [comment]
cc @yakov116 @kidonng
