### ISSUE TITLE
Add `cache.function` mechanism to temporarily skip cache

### ISSUE THREAD

**Issue by fregante** [fregante/webext-storage-cache#18]
Cache is good to avoid slow requests when the data isn't immediately useful, but sometimes you need fresh data.

If you use `cache.get`/`set` you can already implement your own logic, but with `cache.function`, you can't skip the cache.

A "skip cache" mechanism would call the getter function **and** store the result in the cache as usual.

Ideas:

```js
const fn = cache.function(heavyFn);

const value = true or false ? await fn.fresh() : await fn();
```

or better:

```js
const fn = cache.function(heavyFn, {
	needsFreshData: () => true or false
});

const value = await fn();
```

**Comment by notlmn** [comment]
How can the user dynamically decide to either use fresh or stale data?

Any examples?

**Comment by fregante** [comment]
For `bugs-tab` for example:

https://github.com/sindresorhus/refined-github/commit/160804d0589c6b4393b7b5b29a93d33c2a71615c

webext-storage-cache will call `revalidateNow()` before checking the cache. If the function returns true. 

Implementation example:

https://github.com/fregante/webext-storage-cache/commit/20572ea976676e949371c683d02474400bcbd2d7

**Comment by fregante** [comment]
Yes 🙏

**Comment by fregante** [comment]
Uhm, don't we already have one? `shouldRevalidate: () => false` means it will never get from cache. It may not be as convenient as `fn.fresh()` but we can already use it in RG

**Comment by cheap-glitch** [comment]
This is not for RGH but for another extension I'm developing using React. I'd like to keep the cached API helpers outside of the components, which works fine but sometimes I need to ensure data gets refreshed and this would be a good escape hatch for that.
