### ISSUE TITLE
Use objects to define readable expiration values

### ISSUE THREAD

**Issue by fregante** [fregante/webext-storage-cache#19]
These 2 utility functions would make expiration values more readable:

```diff
	const call = cache.function(fn, {
-		maxAge: 1 / 24,
+		maxAge: cache.hours(1),
-		staleWhileRevalidate: 1 / 2
+		staleWhileRevalidate: cache.hours(12)
	});
```

**Comment by notlmn** [comment]
Do we need `cache.days()`, isn't it already the default.

We might as well add `cache.minutes()`, could be useful for chaining `cache.hours(2) + cache.minutes(30)`. WDYT?

**Comment by fregante** [comment]
#16 aims to change that

Minutes sure, but in your example I’d use “2.5” hours instead.

**Comment by sindresorhus** [comment]
Have you considered one method accepting an object of time components? That way you wouldn't need so many methods.

Something like https://github.com/sindresorhus/to-milliseconds

**Comment by fregante** [comment]
Yeah that could work, adding `to-milliseconds` as a dependency of this module
