### ISSUE TITLE
Can't download standalone bundle

### ISSUE THREAD

**Issue by busybox11** [fregante/webext-storage-cache#29]
The webserver serving the standalone bundle doesn't work.
c.f. attached screenshot

![image](https://user-images.githubusercontent.com/29630035/97330174-3177a980-1878-11eb-87a0-52c90fdae145.png)

**Comment by fregante** [comment]
Yeah unfortunately the server stopped working. Related: https://github.com/fregante/webext-dynamic-content-scripts/issues/13

**Comment by fregante** [comment]
The link has been fixed more reliably using https://github.com/fregante/bundler :tada:
