### ISSUE TITLE
[FR] Save into chrome.storage.session and update every new session

### ISSUE THREAD

**Issue by capybarahero** [fregante/webext-storage-cache#44]
Hey @fregante, thanks for building this package! 

How we could have it saved into "chrome.storage.session" instead? 
- i.e. instead of defining a maxAge, the cachedValue/cachedFunction would expire once the session is over.

**Comment by fregante** [comment]
In that case, you don't need to use this package, you can store your data directly into `chrome.storage.session`.

You you like this module's API, you can use `chrome.storage.session` through https://github.com/fregante/webext-storage

```js
const someData = new StorageItem('some-data', {area: 'session'});
