### ISSUE TITLE
Cleaning up cache in Manifest v3

### ISSUE THREAD

**Issue by sb8244** [fregante/webext-storage-cache#48]
I was looking through the code for how chrome.alarms is used, and I see there's a check for `if (!isBackgroundPage())`. This will return in the case of manifest v3, and the alarms and cleanup will not happen.

**Comment by fregante** [comment]
PR welcome to replace it with isBackground

**Comment by sb8244** [comment]
Thank you!

**Comment by fregante** [comment]
I’m computer-less at the moment so I won’t be able to release it this week. For now you might be able to run `npm install fregante/webext-storage-cache` and hope that npm builds it from GitHub.
